cors:
  originPatterns: http://localhost:3000,http://localhost:8080,  https://erudio.com.br
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
    username: root
    password: 281919
  jpa:
    hibernate:
      ddl-auto: none
    #properties:
      #hibernate:
        #dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    open-in-view: false
  spring-doc:
    pathsToMatch: /api/**/v1/**
    swagger-ui:
      use-root-path: true
